(WIP)fix: replace light relay with full relay contracts.
bob-collective/bob pull request #301
Opened 2024-07-31 09:17 UTC by nakul1010

Closes #287

2024-08-16 10:36 UTC, gregdhill requested changes
I don't want to fully replace which relay can be used, should still be possible to use the LightRelay with these utils.

2024-08-16 10:36 UTC, gregdhill commented on src/relay/TestFullRelay.sol
> +contract TestFullRelay is FullRelay {
I'm not entirely sure why we need this contract, could you explain?

2024-09-10 22:55 UTC, Brendabuena2 commented
> Cierra #28 brendabuena2

2025-04-07 16:07 UTC, gregdhill commented
Replaced by https://github.com/bob-collective/bob/pull/545

2025-04-07 16:07 UTC, closed without merging